services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hotel-app
    restart: unless-stopped

    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "http://3.107.34.197:4000"

      DB_CONNECTION: mysql
      DB_HOST: hotel-production-db.cx86ssc8ss6n.ap-southeast-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_DATABASE: hotelDB
      DB_USERNAME: hotel_admin
      DB_PASSWORD: "5kunALp8qKV2WRQ"

  nginx:
    image: nginx:alpine

    container_name: hotel-nginx
    restart: unless-stopped

    ports:
      - "4000:80"

    depends_on:
      - app

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public:ro